# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

  - task: UseDotNet@2
    displayName: 'Install .NET SDK 2.2'
    inputs:
      packageType: 'sdk'
      version: '2.2.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      includePreviewVersions: true

  - task: NuGetToolInstaller@1
    displayName: 'Install Nuget Version'
    inputs:
      versionSpec: '5.4.0'
      checkLatest: true
  
  - task: NuGetCommand@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: 'ApiTeste/ApiTeste.csproj'
      feedsToUse: 'select'
      vstsFeed: 'afe90f0c-37a1-462a-accd-72409983d17f'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build app'
    inputs:
      command: 'build'
      projects: 'ApiTeste/ApiTeste.csproj'
      arguments: '--configuration $(buildConfiguration)'


  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish app'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false

  - task: CopyFiles@2
    displayName: 'copy assets'
    inputs:
     SourceFolder: 'apideteste/'
     Contents: '*.pdf'
     TargetFolder: '$(Build.ArtifactStagingDirectory)/apideteste/'

  - task: ArchiveFiles@2
    displayName: 'archive artifacts'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/apideteste/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'publish build'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      # publishLocation: 'Container'
