


CREATE DATABASE TESTE; 

USE TESTE


/*
CREATE TABLE TB_GENERO_PESSOA (
CODIGO_GENERO INT NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(20) NOT NULL)

INSERT INTO TB_GENERO_PESSOA VALUES (1,'MASCULINO'), (2,'FEMININO')
*/


/*
CREATE TABLE TB_PESSOA (
CODIGO_PESSOA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
IDADE INT NOT NULL,
EMAIL VARCHAR(70) NULL,
SEXO INT NOT NULL FOREIGN KEY REFERENCES TB_GENERO_PESSOA(CODIGO_GENERO),
HABILIDADES VARCHAR(100) NOT NULL,
ATIVO BIT NOT NULL 
)
*/


/*
INSERT INTO TB_PESSOA 
(NOME, 
DATA_NASCIMENTO, 
IDADE, 
EMAIL, 
SEXO, 
HABILIDADES, 
ATIVO)
VALUES ('Karoline Silva Carvalho', 
getdate(), 
21, 
'karoline.transportes@hotmail.com', 
2,
'C#, SQL', 
1)
*/


		